# Generated by Django 3.2.8 on 2021-10-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='load',
            field=models.CharField(choices=[('h', 'high'), ('l', 'low'), ('m', 'medium')], default='l', max_length=1),
        ),
    ]
