# Generated by Django 3.2.8 on 2021-10-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_alter_user_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='administrative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='community',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='research',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='teaching',
            field=models.IntegerField(default=0),
        ),
    ]
