# Generated by Django 3.2.8 on 2021-10-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_auto_20211016_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='experience',
            field=models.CharField(choices=[('fto', '1st_time_teaching_course_overall'), ('fti', '1st_time_teaching_course_at_institution'), ('exp', 'experienced')], max_length=3),
        ),
    ]
